---
- name: Otus ansible hw
  hosts: all
  become: yes

  vars:
    NGINX_PORT: 8080

  tasks:
    - name: Install epel-release repo
      yum:
        name: epel-release
        state: installed

    - name: Install nginx
      yum:
        name: nginx
        state: installed
      notify: restart nginx

    - name: Template nginx default.conf file
      template:
        src: templates/default.conf.j2
        dest: "/etc/nginx/conf.d/default.conf"
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true
      register: restart_status
      until: restart_status is succeeded
